// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8GH6Lx1ylcrzJz9EpVx4ZFcgka8Y73c',
    appId: '1:349851174448:web:01aaf39e7d494db88f0ff5',
    messagingSenderId: '349851174448',
    projectId: 'chatboom-ai-4113c',
    authDomain: 'chatboom-ai-4113c.firebaseapp.com',
    storageBucket: 'chatboom-ai-4113c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2h7i9MjIx39cIk29bTYtYYyZvAleFj1Y',
    appId: '1:349851174448:android:45269e724c5da8b28f0ff5',
    messagingSenderId: '349851174448',
    projectId: 'chatboom-ai-4113c',
    storageBucket: 'chatboom-ai-4113c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lVN4h8wbdVk4fiHYeNShJsYpb2kFltU',
    appId: '1:349851174448:ios:f1e3a9f1ca1f492c8f0ff5',
    messagingSenderId: '349851174448',
    projectId: 'chatboom-ai-4113c',
    storageBucket: 'chatboom-ai-4113c.firebasestorage.app',
    androidClientId: '349851174448-fd3vg01hsn5kv6vig9jneo9ncav8uhp8.apps.googleusercontent.com',
    iosClientId: '349851174448-jb1g08eikj09vrten4fcp9at0mso14km.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatboom',
  );
}
